spring:
  application:
    name: manage
  datasource:
    url: jdbc:mysql:///WMCR?serverTimezone=GMT%2B8&characterEncoding=UTF8
    username: root
    password: 135789
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    
mybatis-plus:
  type-aliases-package: cn.wmxf.pojo
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
    
    
server:
  port: 8080
  servlet:
    context-path: /
 
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka #http://eureka2:2002/eureka
#page
page.config: 
    pageSize: 2 