spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: manage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: cn.wmxf.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level: 
    com.jt.mapper: debug
  
server:
  port: 8080
  servlet:
    context-path: /
 
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka #http://eureka2:2002/eureka
 